version: "3.9"

services: 
  db-ecommerce:
    container_name: postgres
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  ecommerce-api:
    container_name: api
    build: ./api
    env_file:
      - ./api/config/app.env
    ports:
      - "8080:8080"
    depends_on: 
      - db-ecommerce
    environment:
      CHOKIDAR_USEPOLLING: "true"
    volumes: 
      - ./api
    volumes:
      - ./postgres/postgres:/var/lib/postgresql/data

  ecommerce-client:
    container_name: client
    build: ./client
    environment:
      CHOKIDAR_USEPOLLING: "true"
    volumes: 
      - './client:/client/'
      - '/client/node_modules'
    depends_on: 
      - ecommerce-api
    ports:
      - 3000:3000
