version: "3.9"

services: 
  db-ecommerce:
    image: postgres
    environment: 
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  ecommerce-api:
    container_name: api
    build: ./api
    ports:
      - "8080:8080"
    depends_on: 
      - db-ecommerce
